require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListContactsController do

  # This should return the minimal set of attributes required to create a valid
  # ListContact. As you add validations to ListContact, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all list_contacts as @list_contacts" do
      list_contact = ListContact.create! valid_attributes
      get :index
      assigns(:list_contacts).should eq([list_contact])
    end
  end

  describe "GET show" do
    it "assigns the requested list_contact as @list_contact" do
      list_contact = ListContact.create! valid_attributes
      get :show, :id => list_contact.id.to_s
      assigns(:list_contact).should eq(list_contact)
    end
  end

  describe "GET new" do
    it "assigns a new list_contact as @list_contact" do
      get :new
      assigns(:list_contact).should be_a_new(ListContact)
    end
  end

  describe "GET edit" do
    it "assigns the requested list_contact as @list_contact" do
      list_contact = ListContact.create! valid_attributes
      get :edit, :id => list_contact.id.to_s
      assigns(:list_contact).should eq(list_contact)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ListContact" do
        expect {
          post :create, :list_contact => valid_attributes
        }.to change(ListContact, :count).by(1)
      end

      it "assigns a newly created list_contact as @list_contact" do
        post :create, :list_contact => valid_attributes
        assigns(:list_contact).should be_a(ListContact)
        assigns(:list_contact).should be_persisted
      end

      it "redirects to the created list_contact" do
        post :create, :list_contact => valid_attributes
        response.should redirect_to(ListContact.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved list_contact as @list_contact" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListContact.any_instance.stub(:save).and_return(false)
        post :create, :list_contact => {}
        assigns(:list_contact).should be_a_new(ListContact)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ListContact.any_instance.stub(:save).and_return(false)
        post :create, :list_contact => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested list_contact" do
        list_contact = ListContact.create! valid_attributes
        # Assuming there are no other list_contacts in the database, this
        # specifies that the ListContact created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ListContact.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => list_contact.id, :list_contact => {'these' => 'params'}
      end

      it "assigns the requested list_contact as @list_contact" do
        list_contact = ListContact.create! valid_attributes
        put :update, :id => list_contact.id, :list_contact => valid_attributes
        assigns(:list_contact).should eq(list_contact)
      end

      it "redirects to the list_contact" do
        list_contact = ListContact.create! valid_attributes
        put :update, :id => list_contact.id, :list_contact => valid_attributes
        response.should redirect_to(list_contact)
      end
    end

    describe "with invalid params" do
      it "assigns the list_contact as @list_contact" do
        list_contact = ListContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListContact.any_instance.stub(:save).and_return(false)
        put :update, :id => list_contact.id.to_s, :list_contact => {}
        assigns(:list_contact).should eq(list_contact)
      end

      it "re-renders the 'edit' template" do
        list_contact = ListContact.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ListContact.any_instance.stub(:save).and_return(false)
        put :update, :id => list_contact.id.to_s, :list_contact => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested list_contact" do
      list_contact = ListContact.create! valid_attributes
      expect {
        delete :destroy, :id => list_contact.id.to_s
      }.to change(ListContact, :count).by(-1)
    end

    it "redirects to the list_contacts list" do
      list_contact = ListContact.create! valid_attributes
      delete :destroy, :id => list_contact.id.to_s
      response.should redirect_to(list_contacts_url)
    end
  end

end
